name: SFWaveTides
options:
  bundleIdPrefix: com.example

targets:
  SFWaveTides:
    type: application
    platform: iOS
    sources:
      - SFWaveTides
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SFWaveTides
        PRODUCT_NAME: SFWaveTides
        SWIFT_VERSION: 5.9

  SFWaveTidesWatch:
    type: application.watchapp2
    platform: watchOS
    sources:
      - SFWaveTidesWatch/Watch
      - SFWaveTidesWatch/Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SFWaveTides.watchkitapp
        PRODUCT_NAME: SFWaveTidesWatch
        SWIFT_VERSION: 5.5
        SDKROOT: watchos
